[package]
name = "chumsky-proc-macro"
version = "0.1.0"
edition = "2024"

[dependencies]
chumsky = "1.0.0-alpha.8"
proc-macro2 = "1.0.95"
syn = { version = "2.0.101", optional = true }

[features]
syn = ["dep:syn"]


[dev-dependencies]
quote = "1.0.40"

